### ISSUE TITLE
Mopping mode on Xiaomi Robot Vacuum 2

### ISSUE THREAD

**Issue by nuc134r** [marcelrv/XiaomiRobotVacuumProtocol#16]
Mopping mode is set in the same section as suction power (fan level) in Mi Home app. It also says that it decreases suction a lot (it warns that it will be only set for the next cleaning session and then will change to previous mode). I guess it also changes the way robot moves to mop efficiently. 

I wonder how would you set it through protocol. I will update this issue once I'll get any info about mopping mode and how to set it using miio protocol.

Any tips on capturing Mi Home app traffic on non-rooted device?

**Comment by nuc134r** [comment]
https://github.com/Hypfer/Valetudo/issues/5

Some people say that `105` as fan speed is actually a mopping mode.

**Comment by marcelrv** [comment]
yes, it was confirmed recently sending 105 change the mode to mop
The modes are 101,102,103,104,105.

**Comment by marcelrv** [comment]
I received some facts about the washing operation:

It seems that the vacuum doesn’t control the water release because there are no buses/wires on the water tank and the two valves under the mop release the water anyway (as a matter of fact mine one releases water also in “just-vacuum” mode): if you want no water, you have to remove the tank;
The “mop mode” seems to be just a mode in wich the vacuum moves slower than in the other modes and with a power of the fan reduced.
I tried giving 105 over the  fan channel and the robot seems to perform as I wrote in the second point.

**Comment by FeatureExpert** [comment]
As marcelrv said, you can set mop mode by setting fan_power to 105:

```{'method': 'props', 'id': 666, 'params': {'fan_power': 105}}```

But according to my logs other modes are slightly different:

Quiet --> fan_power: 38
Balanced --> fan_power: 60
Turbo --> fan_power: 75
Max --> fan_power: 100
